config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  post '/login' => 'login#create'
  delete '/logout' => 'login#destroy'
  get '/register' => 'registration#new'
  post '/register' => 'registration#create'
  get '/search' => 'site#search'
  get '/report' => 'site#report'

  resources :items do
  	post '/relations' => 'relations#create'
    post '/questions' => 'questions#create'
  	get '/relations/:id' => 'relations#authenticate', as: "relation"
    post '/relations/:id' => 'relations#answer', as: "answer"
    patch '/questions/:id' => 'questions#validate_answer', as: "question"
  end

end

app/views/shared/_main_footer.html.erb
		<footer class="footer-page-fixed">
			<p>All Rights 
				<b>Reserved 2015</b>
				<span class="glyphicon glyphicon-copyright-mark"></span>
			</p>
		</footer>
	</body>
</html>

app/views/shared/_main_footer_design.html.erb
		<footer class="footer-page-fixed">
      <div class="row">
        <p>© COPYRIGHT OWMI 2015 | <a href="">TÉRMINOS Y CONDICIONES DE USO</a></p>
        <span><img src="#" alt=""></span>
      </div>
		</footer>
	</body>
</html>

app/views/shared/_main_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecoverMe</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  	<!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="container">
        <form class="form-inline">
          <a class="navbar-brand" href=<%= root_path.to_s %>>Recover Me</a>
          <%=
            link_to "Report Lost Object", new_item_path+"?reporting=lost", id: "report-lost-object", class: "btn btn-default navbar-btn"
          %>
          <%=
            link_to "Report Found Object", new_item_path+"?reporting=found", id: "report-found-object", class: "btn btn-default navbar-btn"
          %>
          <%= link_to "Register User", register_path, class: "btn btn-default navbar-btn" %>
          <div class="form-group">
            <label for="exampleInputName2">Name</label>
            <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail2">Email</label>
            <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
          </div>
          <button type="submit" class="btn btn-default">Send invitation</button>
        </form>
      </div>
    </div>
    <!-- -->
  </div>
</nav>

app/views/shared/_navbar_login.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-user"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag("https://dl.dropboxusercontent.com/u/10924302/recover-me/logo_sm.png", class: "top-left-brand", alt: "Owmi Logo") %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <% if session[:logged_in_user] %>
        <div class="logged-in-container">
          <%= current_user.name %> -
          <%= link_to "Log out", logout_path, method: :delete %>
          <%= image_tag("https://dl.dropboxusercontent.com/u/10924302/recover-me/login.png", class: "image-login", alt: "Edit Entry") %>
        </div>
      <% else %>
        <%= form_tag login_path, class: "navbar-form navbar-right" do %>
          <div class="form-group">
            <%= label :email, "Email" %>
            <%= text_field_tag "email", nil, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label :password, "Password" %>
            <%= password_field_tag "password", nil, class: "form-control" %>
          </div>
          <%= submit_tag "Log In", class: "btn btn-default" %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_navbar_login_design.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand" href="#">
        <img alt="Brand" src="http://www.owmi.co/images/btn-menu.png">
      </a>


      <div class="navbar-social-container">
        <a class="navbar-social" href="#">
          <img alt="social 1" src="http://www.owmi.co/images/icon-play.png">
        </a>
        <a class="navbar-social" href="#">
          <img alt="social 1" src="http://www.owmi.co/images/icon-twitter.png">
        </a>
        <a class="navbar-social" href="#">
          <img alt="social 1" src="http://www.owmi.co/images/icon-facebook.png">
        </a>
        <a class="navbar-social" href="#">
          <img alt="social 1" src="http://www.owmi.co/images/icon-email.png">
        </a>

        <div class="navbar-login-container">
          <a href="">
            <img src="http://www.owmi.co/images/icon-login.png" alt="">
            <p>Login</p>
            <img src="http://www.owmi.co/images/arrow-bottom.png" alt="Login Info">
          </a>
        </div>


      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="#">Link</a></li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navbar_login_error.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  	<!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="container col-md-offset-1">
        <a class="navbar-brand" href=<%= root_path.to_s %>>Recover Me</a>
        <%= 
					link_to "Report Lost Object", new_item_path+"?reporting=lost", id: "report-lost-object", class: "btn btn-default navbar-btn" 
				%>
				<%= 
					link_to "Report Found Object", new_item_path+"?reporting=found", id: "report-found-object", class: "btn btn-default navbar-btn" 
				%>
        <%= link_to "Register User", register_path, class: "btn btn-default navbar-btn" %>
        <% if @user.empty? %>
        <p class="navbar-text navbar-right">Not logged in</p>
        <% else %>
        <%= link_to "Log out", logout_path, method: :delete, class: "navbar-text navbar-right" %>
        <p class="navbar-text navbar-right">Signed in as <%= @user[0].name %></p>
        <% end %>
      </div>
    </div>
    <!-- -->
  </div>
</nav>