config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  post '/login' => 'login#create'
  delete '/logout' => 'login#destroy'
  get '/register' => 'registration#new'
  post '/register' => 'registration#create'
  get '/search' => 'site#search'
  get '/report' => 'site#report'

  resources :items do
  	post '/relations' => 'relations#create'
    post '/questions' => 'questions#create'
  	get '/relations/:id' => 'relations#authenticate', as: "relation"
    post '/relations/:id' => 'relations#answer', as: "answer"
    patch '/questions/:id' => 'questions#validate_answer', as: "question"
  end

end

app/models/item.rb
class Item < ActiveRecord::Base

	validates :name, presence: true, length: { in: 2..150 }
	validates :datetime, presence: true
  validates :contact_email, presence: true
  validates_format_of :contact_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  has_attached_file :avatar, :styles => { :big => "900x900>", :medium => "300x300>", :thumb => "100x100>" },
                                          :default_url => "system/images/missing.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  scope :has_reward,  -> { where("reward IS NOT NULL").order("datetime DESC") }
  scope :lost, 		 		-> { where(state: "lost").order("datetime DESC") }
  scope :found,				-> { where(state: "found").order("datetime DESC") }
  scope :resolved, 		-> { where(state: "resolved").order("datetime DESC") }

  has_many :relations
  has_many :owners
  has_many :founders
  has_many :questions
  has_many :users, through: :relations

  accepts_nested_attributes_for :relations
  accepts_nested_attributes_for :owners
  accepts_nested_attributes_for :questions

  def is_lost?
    return true if (state == "Lost")
    false
  end

  def is_found?
    return true if (state == "Found")
    false
  end

  def is_resolved?
    return true if (state == "Resolved")
    false
  end

  def self.search(search)
    if search
      Item.where("name like ?", "%#{search}%")
    end
  end

  def self.get_lost_items_by_user_id(user_id)
    items_by_user_id = []
    Owner.where("user_id = ?", user_id).all.each do |owner|
      items_by_user_id << owner.item
    end  
    items_by_user_id
  end

  def self.get_found_items_by_user_id(user_id)
    items_by_user_id = []
    Founder.where("user_id = ?", user_id).all.each do |founder|
      items_by_user_id << founder.item
    end  
    items_by_user_id
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_action :require_login
	helper_method :is_current_user_owner?
	helper_method :is_current_user_founder?

	def index
		# all relations for current user
		@my_relations = Relation.get_by_user_id(session[:logged_in_user])
		# all item ids for current user - can be inside items
		my_item_ids = @my_relations.map(&:item_id)
		# all item requests by other users over my items
		@item_requests = get_item_requests(my_item_ids)
		#got to check new messages - pending validations - pending questions - etc!
		@other_relations = Relation.where("user_id != ?", current_user.id)
		#@lost_items = Item.all
		@lost_items = get_current_lost_items

		#for creating new reports
		@item = Item.new
		@relation = @item.relations.new

		#user lost & found
		@user_lost_items = Item.get_lost_items_by_user_id(current_user.id)
		@user_found_items = Item.get_found_items_by_user_id(current_user.id)
	end

	def get_item_requests( items_ids )
		# get relations over item without the current user... this means requests / item matches by other users
		r_ary = []
		items_ids.each do |item_id|
			r_ary << Relation.get_by_item_without_user(current_user.id, item_id)
		end
		r_ary
	end

	def new
		session["reporting"] = get_reporting_status
		if session["reporting"] == "lost"
			@is_reporting_lost = true
		elsif session["reporting"] == "found"
			@is_reporting_lost = false
		end
		@item = Item.new
	end

	def create

		@item = Item.new item_params
		@item.relations.first.user_id = session[:logged_in_user]

		if @item.save
			flash["success_message"] = "Report created succesfully."
			#redirect_to items_path
			redirect_to item_path(@item)
		else
			flash[:danger_message] = @item.errors.full_messages
			#redirect_to items_path
		end		
	end

	def show

		@user = current_user
		@item = Item.where(id: params[:id])[0]

		if @item.founders.where(user_id: @user.id).empty? == false
			@relation_ship_type = "founder"
		elsif @item.owners.where(user_id: @user.id).empty? == false
			@relation_ship_type = "owner"
		else
			@relation_ship_type = nil
		end
	end

	def destroy
		item = Item.find(params[:id])
		Relation.where(item_id: item.id).destroy_all
		item.destroy
		flash.now["info_message"] = "Report deleted succesfully."
		redirect_to items_path
	end

	def update
		item = Item.find(params[:id])
		item.update!(item_update_params)
    redirect_to item		
	end

	private

	def is_current_user_owner?
		return true if @item.owners.first.user.id == @user.id
		false
	end

	def is_current_user_founder?
		@item.founders.each do |founder|
			return true if @user.id == founder.user.id
		end
		false
	end

	def get_reporting_status
		params["reporting"]
	end

	def item_params
		params.require(:item).permit(:name,:avatar,:datetime,:contact_email,:state,:description,:reward,:category,relations_attributes:[:id, :type])
  end

  def item_update_params
		params.require(:item).permit(:description,:reward,:category)
  end

  def get_current_lost_items
		all_items = Item.all
		relations = []
		item_results = []
		all_items.each do |item|
			if item.relations.length > 1
				item.relations.each do |relation|
					relations << relation.ownership_validated?
				end
				if relations.include? false
					item_results << item
				else
					p 'already validated relation....'
				end
			else
				item_results << item
			end
		end
		item_results
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_all_items.html.erb
<div class="list-group">
  <% if @lost_items.any? %>
    <% @lost_items.each do |item| %>
      <a href=<%= item_path(item) %> class="list-group-item">
      <h4 class="list-group-item-heading">
        <b><span class="item-name"><%= item.name %></span></b>
      </h4>
        <div class="media">
          <div class="media-left">
            <img class="media-object object-image" src=<%=item.avatar.url(:thumb)%> alt="...">
          </div>
          <div class="media-body">
            <p>
              Reported 
              <b><%= item.state %></b> in: <b><%= item.created_at.strftime("%m/%d/%Y at %I:%M%p") %></b>
            </p>
          </div>
        </div>
      </a>
    <% end %>
  <% else %>
    <p>There are currently no items reported.</p>
  <% end %>
</div>

app/views/items/_item_found_requests.html.erb
<% if relation.item.founders.first.user.id == current_user.id %>

	<p>
    <b><%= relation.item.name %></b> you reported 
    <b>found </b> on
    <b><%= relation.item.founders.first.created_at.strftime("%m/%d/%Y at %I:%M%p") %></b>
  </p>
  <hr>

  <% relation.item.owners.first.user.answers.each do |answer| %>

	  <p>Question: <b><%= answer.question.name %></b></p>
	  <p>Correct Answer: <b><%= answer.question.answer %></b></p>
	  <p>Respuesta de <b><%= answer.user.name %></b>: <b><%= answer.answer %></b></p>

	  <% if answer.is_validated.nil? %>
		  <%= form_tag( item_question_path(relation.item.id, answer.question.id), method: :patch) do %>
		  <%= hidden_field_tag :answer_id, answer.id %>
		  <%= hidden_field_tag :is_validated, true %>
		  <%= submit_tag "Valid Answer", class: "btn btn-default" %>
		  <% end %>

		  <%= 
		  	form_tag( item_question_path(relation.item.id, answer.question.id), method: :patch) do 
		  %>

		  <%= hidden_field_tag :answer_id, answer.id %>
		  <%= hidden_field_tag :is_validated, false %>
		  <%= submit_tag "Invalid Answer", class: "btn btn-default" %>
	  	<% end %>

		<% else %>
			<% if answer.is_validated == true %>
				<p>You've already APPROVED this answer.</p>
			<% else %>
				<p>You've already DISAPPROVED this answer.</p>
			<% end %>
		<% end %>
		<hr>
	<% end %>

	<% if relation.item.questions.length < 3 %>

		<p>
	  	Ask at the most three (3) precise things for <b><%= relation.item.owners.first.user.name %></b> to validate the ownership of the object.
	  </p>

	  <%= link_to "Create questions", item_relation_path(relation.item.id, Relation.get_by_userid_and_itemid(relation.item.owners.first.user.id, relation.item.id)[0])
	  %>

	<% else %>
		<p><b>Questions already created for ownership validation.  Limit reached (3/3)</b></p>
		

	<% end %>

<% else %>

	<!-- existe relaciones de otros usuarios con mis reportes -->
  <!-- evaluar si el item fue reportado perdido o encontrado por mi -->
  <!-- ESTO YA ESTA HECHO EN OTRA LISTA! -->

	<p>
    <b><%= relation.item.name %></b> you reported 
    <b>lost </b> on
    <b><%= relation.item.created_at.strftime("%m/%d/%Y at %I:%M%p") %></b>
  </p>

  <% relation.item.founders.each do |founder| %>
    <p>Appears to have been found by:</p>
    <p><b><%= founder.user.name %></b></p>
    <p>Contact him in:
      <b><%= founder.user.email %></b>
    </p>
		<% if relation.item.questions.any? %>
			<hr>
      <h4>There are questions for you to validate your ownership...</h4>
        <% relation.item.questions.each_with_index do |question, i| %>
          <div>
            <p>Question <%= i + 1 %>: <b><%= question.name %></b></p>
            <% if question.already_answerd?(current_user.id) %>
	            <p><b>Your answer was:</b></p>
	            <p><%= question.get_answer_by_user_id(current_user.id) %></p>
	           
						<% if question.is_answer_validated?(current_user.id).nil? %>
							<p><b><%= founder.user.name %> have not validated your answer yet.</b></p>	
						<% else %>

							<% if question.is_answer_validated?(current_user.id) %>	
								<p><b><%= founder.user.name %> already APPROVED your answer.</b></p>	
								<% else %>
								<p><b><%= founder.user.name %> already DISAPPROVED your answer.</b></p>	
								<% end %>
            <% end %>

            <% else %>

            <%= form_tag item_answer_path(relation.item, relation) do %>
            <div class="form-group">
              <%= label :answer, "Answer:" %>
              <%= text_area_tag :answer, nil, class: "form-control" %>
            </div>
            <%= hidden_field_tag :question_id, question.id %>
            <%= submit_tag "Answer question", class: "btn btn-default" %>
            <% end %>
            <% end %>
          </div>
          <hr>
        <% end %>




				<!-- 
					WATCHHH OUT DEAD END
				-->

	      <%
			if Answer.validate_all_by_userid_and_relationid(
				 relation.item.owners.first.user.id,
				 relation.item.owners.first.user.answers.first.relation_id)
				%>

				<%#= submit_tag "Claim Item!", class: "btn btn-default" %>

				<p>
					<b><%= relation.item.founders.first.user.name %></b> validated all your answers. It appears that you recovered <b><%= relation.item.name %>!</b><br><br>To colect your belongings contact: 
					<b><%= relation.item.founders.first.user.email %></b>
				</p>
				<% else %>
				<p>
					Unfortunately <b><%= relation.item.founders.first.user.name %></b> (email: <b><%= relation.item.founders.first.user.email %></b>) has not validated all your answers. It appears that <b><%= relation.item.name %></b> does not belong to you.   
				</p>
				<% end %>






      <% else %>
      <p>There are NO questions for you</p>
      <p>Request them to the founder of your object...</p>
    <% end %>
  <% end %>
<% end %>

app/views/items/_item_lost_requests.html.erb
<% if relation.item.owners.first.user.id == current_user.id %>

	<p>
    <b><%= relation.item.name %></b> you reported 
    <b>lost </b> on
    <b><%= relation.item.founders.first.created_at.strftime("%m/%d/%Y at %I:%M%p") %></b>
  </p>
  <hr>
  <p>Apparently its been found by:</p>
  <p><b><%= relation.item.founders.first.user.name %></b></p>
  <hr>
  <% if relation.item.questions.any? %>

		<% if relation.item.questions.length < 3 %>

				<p>
			  	You must answer three (3) precise and wait until they've been validated to claim your object.
			  </p>

			<% else %>

				<% if relation.item.owners.first.user.answers.length == 3 %>

				<% if Answer.validate_all_by_userid_and_relationid(
					 relation.item.owners.first.user.id,
					 relation.item.owners.first.user.answers.first.relation_id) == true
					%>

				<div class="alert alert-success" role="alert">
			    <p>
		        <b><%= relation.item.founders.first.user.name %></b> validated all your answers. It appears that you recovered <b><%= relation.item.name %>!</b><br><br>To colect your belongings contact: 
		        <b><%= relation.item.founders.first.user.email %></b>
		      </p>
			  </div>

		    <% elsif Answer.validate_all_by_userid_and_relationid(
					 relation.item.owners.first.user.id,
					 relation.item.owners.first.user.answers.first.relation_id) == false
					%>

				<div class="alert alert-warning" role="alert">
					<p>
		        Unfortunately <b><%= relation.item.founders.first.user.name %></b> (email: <b><%= relation.item.founders.first.user.email %></b>) has not validated all your answers. It appears that <b><%= relation.item.name %></b> does not belong to you.   
		      </p>
			  </div>
	   
	    	<% end %> 	
	    <% end %> 
		<% end %>



	<hr>
    <% relation.item.questions.each_with_index do |question, i| %>
      <div>

        <p>Q<%= i + 1 %>: <b><%= question.name %></b></p>


        <% if question.already_answerd?(current_user.id) %>

        <p>You have answered "
        <b><%= question.get_answer_by_user_id(current_user.id) %>"</b> 
        for that question.</p>


	        <% if question.is_answer_validated?(current_user.id) == true %>
	        <p><b><%= relation.item.founders.first.user.name %> APPROVED your answer.</b></p> 
	        <% elsif question.is_answer_validated?(current_user.id) == false %>
	        <p><b><%= relation.item.founders.first.user.name %> DISAPPROVED your answer.</b></p> 
	        <% elsif question.is_answer_validated?(current_user.id) == nil %>
					<p><b><%= relation.item.founders.first.user.name %></b> has not yet validated your answer.</p> 
	        <% end %>
        <% else %>
	        <%= form_tag item_answer_path(relation.item, relation) do %>
	        <div class="form-group">
	          <%= label :answer, "Answer..." %>
	          <%= text_area_tag :answer, nil, class: "form-control" %>
	        </div>
	        <%= hidden_field_tag :question_id, question.id %>
	        <%= submit_tag "Answer question", class: "btn btn-default" %>
        	<% end %>
        <% end %>
      </div>
      <hr>
    <% end %>

    
    

  <% else %>
  <hr>
  <p><b>There are no questions yet</b> to validate this item ownership.</p>
  <% end %>


<% else %>

	<p>
    You've found <b><%= relation.item.name %></b> on
    <%= relation.item.founders.first.created_at.strftime("%m/%d/%Y at %I:%M%p") %>
  </p>

  <% if relation.item.questions.length < 3 %>
		<p>
	  	Ask three (3) precise things for <b><%= relation.item.owners.first.user.name %></b> to validate the ownership of the object.
	  </p>
  <%= link_to "Create questions", item_relation_path(relation.item.id,
		Relation.get_by_userid_and_itemid(relation.item.owners.first.user.id, relation.item.id)[0])
  %>
	<% else %>

		<p><b>Questions created for ownership validation.  Limit reached (3/3)</b></p>

		<% if relation.item.owners.first.user.answers.length == 3 %>

			<% if Answer.validate_all_by_userid_and_relationid(
					 relation.item.owners.first.user.id,
					 relation.item.owners.first.user.answers.first.relation_id) == true
					%>

			<div class="alert alert-success" role="alert">
		    <p>
		      <b> You have validated all <%= relation.item.owners.first.user.name %> answers. It appears that you encountered <%= relation.item.name %>!</b> owner.<br><br><b>Contact:<br><%= relation.item.owners.first.user.email %></b>
		    </p>
		  </div>

			<% elsif Answer.validate_all_by_userid_and_relationid(
					 relation.item.owners.first.user.id,
					 relation.item.owners.first.user.answers.first.relation_id) == false
					%>

			<div class="alert alert-warning" role="alert">
		     <p>You have invalidated answers by <b><%= relation.item.founders.first.user.name %></b> (email: <b><%= relation.item.founders.first.user.email %></b>)<br><br>It appears that <b><%= relation.item.name %></b> does not yet have a correct owner.
	    </p>
		  </div>
   
    	<% end %> 
		<% end %>
	<% end %>

	<hr>	

	<% relation.item.owners.first.user.answers.each do |answer| %>

	  <p>Q: <b><%= answer.question.name %></b></p>
	  <p><b><%= answer.user.name %></b> answered: <b><%= answer.answer %></b></p>

	  <% if answer.is_validated.nil? %>
		  <%= form_tag( item_question_path(relation.item.id, answer.question.id), method: :patch) do %>
		  <%= hidden_field_tag :answer_id, answer.id %>
		  <%= hidden_field_tag :is_validated, true %>
		  <%= submit_tag "Valid Answer", class: "btn btn-default" %>
		  <% end %>

		  <%= 
		  	form_tag( item_question_path(relation.item.id, answer.question.id), method: :patch) do 
		  %>

		  <%= hidden_field_tag :answer_id, answer.id %>
		  <%= hidden_field_tag :is_validated, false %>
		  <%= submit_tag "Invalid Answer", class: "btn btn-default" %>
	  	<% end %>

		<% else %>

			<% if answer.is_validated %>
				<p>You've <b>APPROVED</b> this answer.</p>
			<% else %>		
				<p>You've checked this answer as <b>WRONG</b>.</p>
			<% end %>		

		<% end %>
		<hr>
	<% end %>


<% end %>

app/views/items/_report.html.erb
<%= form_for( Item.new, url: items_path ) do |f| %>

<% if @is_reporting_lost %>
<h1>Report Lost Item</h1>
<% else %>
<h1>Report Found Item</h1>
<% end %>

<div class="form-group">
  <%= f.label :name, "Product Name" %>
  <%= f.text_field :name, placeholder: "Ej. Passport", class: "form-control" %>
</div>

<% if @is_reporting_lost %>
<div class="form-group">
  <%= f.label :datetime, "Date when I lost the object" %>
  <%= f.date_field :datetime, class: "form-control" %>
</div>
<% else %>
<div class="form-group">
  <%= f.label :datetime, "Date when I found the object" %>
  <%= f.date_field :datetime, class: "form-control" %>
</div>
<% end %>

<div class="form-group">
  <%= f.label :contact_email, "Contact Email" %>
  <%= f.text_field :contact_email, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :category, "Category" %>
  <%= f.text_field :category, class: "form-control" %>
</div>

<% if @is_reporting_lost %>
<div class="form-group">
  <%= f.label :reward, "I will give to the one that returns this item the following: " %>
  <%= f.text_field :reward, placeholder: "50€", class: "form-control" %>
</div>
<% end %>

<% if @is_reporting_lost %>
<div class="form-group">
  <%= f.label :description, "Brief description of how you lost your object (if any):" %>
  <%= f.text_area :description, class: "form-control" %>
</div>
<% else %>
<div class="form-group">
  <%= f.label :description, "Brief description of how you fond the object (if any):" %>
  <%= f.text_area :description, class: "form-control" %>
</div>
<% end %>
<%= f.submit "Report!", class: "btn btn-default" %>
<% end %>

app/views/items/_report_lost.html.erb
<%= form_for @item, url: items_path, :html => { :multipart => true } do |f| %>
  <%= f.hidden_field(:state, value: "Lost") %>
  <div class="form-group">
    <%= f.label :name, "* Object Name" %>
    <%= f.text_field :name, placeholder: "E.g. The One Ring", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :avatar, "Image" %>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-group">
    <%= f.label :datetime, "* Date when I lost the object" %>
    <%= f.date_field :datetime, value: Date.today, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :contact_email, "* Contact Email" %>
    <%= f.text_field :contact_email, value:current_user.email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :reward, "Reward" %>
    <%= f.text_field :reward, placeholder: "E.g. A really big hug", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category, "Category" %>
    <%= f.text_field :category, placeholder: "Please not jewelry...", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Brief description of how you found the object:" %>
    <%= f.text_area :description, placeholder: "If any...", class: "form-control" %>
  </div>

  <%= f.fields_for :relations do |relation_fields| %>
    <%= relation_fields.hidden_field(:type, value:"Owner") %>
  <% end %>

  <%= f.submit "Report!", class: "btn btn-success btn-lg pull-right" %>
<% end %>

app/views/items/_report_lost_additional.html.erb
<%= form_for(@item, url: item_path(@item), html: {method: "patch"}) do |f| %>

  <div class="form-group">
    <%= f.label :reward, "Reward" %>
    <%= f.text_field :reward, placeholder: "E.g. A really big hug", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category, "Category" %>
    <%= f.text_field :category, placeholder: "Please not jewelry...", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Brief description of how did you lost the object:" %>
    <%= f.text_area :description, placeholder: "If any...", class: "form-control" %>
  </div>

  <%= f.submit "Save Additional Info", class: "btn btn-success btn-lg pull-right" %>
  
  <br><br>

<% end %>

app/views/items/_search_form.html.erb
<div class="search-main-title">

  <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
    <div class="big-image-logo">
      <img src="https://dl.dropboxusercontent.com/u/10924302/recover-me/logo.png" alt="Owmi Logo" class="img-responsive">
    </div>
  </div>

  <div class="col-xs-12 col-md-10 col-md-offset-1">

    <%= form_tag search_path, :method => 'get' do %>
      <%=
        text_field_tag :search, params[:search],
        placeholder: "Lost something? Search it here...", class: "form-control search-form"
      %>
      <%= submit_tag "Search", :name => nil, class: "btn btn-success btn-lg pull-right search-btn" %>
      <div>
        <p class="eg-search-box">e.g. Passport John Doe</p>
      </div>
    <% end %>

  </div>
</div>

app/views/items/index.lists.html.erb
<div class="col-md-12">
	<div class="col-md-8 col-md-offset-2">
		<div>
		  <h2>List of requests</h2>
		  <p>All my items that I have reported and have been requested</p>
		  <p>Only requests from other users</p>
		  <div class="list-group">
		  <% @item_requests.each do |ar_relation| %>
		  	<% if ar_relation.any? %>
			  	<% ar_relation.each do |relation| %>
					<a href="" class="list-group-item">

				    <h4 class="list-group-item-heading">
				    	Item Request: <b><%= relation.item.name %></b>
				    </h4>

				    <% if relation.item.is_lost? %>
						<p>Relation ID: <b><%= relation.id %></b></p>
				    <p>Item reported: <b><%= relation.item.state %></b></p>
				    <p>By: <b><%= relation.item.owners.first.user.name %></b></p>
						<hr>
				    <p>Appears to have been found by:</p>
				    <p><b><%= relation.item.founders.first.user.name %></b></p>
				    <p>Contact him in:
				    	<b><%= relation.item.founders.first.user.email %></b>
				    </p>
				  	<% end %>

				  	<% if relation.item.is_found? %>
						<p>Relation ID: <b><%= relation.id %></b></p>
				    <p>Item reported: <b><%= relation.item.state %></b></p>
				    <p>By: <b><%= relation.item.founders.first.user.name %></b></p>
						<hr>
							<!-- if the founder of the item is me I have to authenticate -->
					    <% if relation.item.founders.first.user.id == current_user.id  %>
						    <% relation.item.owners.each do |owner| %>
							    <p>Appears to have been lost by:</p>
							    <p><b><%= owner.user.name %></b></p>
							    <p>Contact him in:
							    	<b><%= owner.user.email %></b>
							    </p>
							    <p><%= owner.user.id %></p>
							    <p>Item name: <%= relation.item.id %></p>
							    <p>Validate this relationship:</p>
							    <p>
								    <%=
								    	Relation.get_by_user_and_item(owner.user.id, relation.item.id)[0].id
								    %>
							    </p>
									<%= link_to "Validate Ownership", item_relation_path(relation.item.id,
										Relation.get_by_user_and_item(owner.user.id, relation.item.id)[0])
									%>
							  <% end %>
							<% else %>
								<p>You can't validate a item that is not found by you</p>
						  <% end %>
						<% end %>
				  </a>
				  <% end %>
			  <% end %>
		  <% end %>
		  </div>
		</div>
		<!--
		<div>
		  <h2>Choose report</h2>
		  <p>Lost / Found / I no longer need this... / I am in the need of...</p>
		  <%# = render :partial => '/items/report_lost' %>
		  <%# = render :partial => '/items/report_found' %>
		</div>
		-->
		<hr>
		<div>
		  <h2>List of lost reported objects</h2>
		  <p>All items reported lost / later the nearby should be placed here</p>
		</div>
		<div class="list-group">
			<% @lost_items.each do |item| %>
			  <a href=<%= item_path(item) %> class="list-group-item">
			    <h4 class="list-group-item-heading">Item:
			    	<b><span class="item-name"><%= item.name %></span></b>
			    </h4>
			    <p class="list-group-item">Contact Email: <b><%= item.contact_email %></b></p>

			    <p class="list-group-item">State: <b><%= item.state %></b></p>
			    <p class="list-group-item">Reward: <b><%= item.reward %></b></p>
			    <p class="list-group-item">Coordinates - Lat:
			    	<b><span class="item-latitude"><%= item.latitude %></span></b> /
			    	Lon: <b><span class="item-longitude"><%= item.longitude %></span></b>
			    </p>
			  </a>
			<% end %>
		</div>
		<div>

		<!--
			<div id="map-container"></div>
		-->

		</div>
		<hr>
	</div>
</div>

app/views/items/search.html.erb
<div class="col-md-12">
	<div class="col-md-8 col-md-offset-2">
		<h2>Search results</h2>
	</div>
</div>

app/views/items/show.html.erb
<div class="col-md-12">
	<div class="col-md-8 col-md-offset-2">
		<div class="item-show-container">

			<h2><b><%= @item.name %></b></h2>
			<%= image_tag @item.avatar.url(:medium), class: "img-responsive" %>
			<p>Contact Email: <%= @item.contact_email %></p>
			<hr>

			<% if is_current_user_owner? %>

				<h3>Additional Information</h3>
				<p>Enter any more information about the object you reported lost to help possible founders to validate your ownership, this information is optional for you to enter; anyhow while more information given more possibilities you have to recover your lost object.</p>

				<%= render :partial => '/items/report_lost_additional' %>

			<% else %>

				<% if is_current_user_founder? %>
					<p>You already have a report as founder of this item.</p>
				<% else %>
					<%= form_tag item_relations_path(@item, @relation) do %>
					<%= hidden_field_tag :user_id, current_user.id %>
					<%= submit_tag "I have found this item", class: "btn btn-default" %>
					<% end %>
				<% end %>				
			<% end %>

			<hr>
			<%= link_to "Back to items...", items_path, class: "btn btn-default" %>
			<hr>

		</div>
	</div>
</div>