config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  post '/login' => 'login#create'
  delete '/logout' => 'login#destroy'
  get '/register' => 'registration#new'
  post '/register' => 'registration#create'
  get '/search' => 'site#search'
  get '/report' => 'site#report'

  resources :items do
  	post '/relations' => 'relations#create'
    post '/questions' => 'questions#create'
  	get '/relations/:id' => 'relations#authenticate', as: "relation"
    post '/relations/:id' => 'relations#answer', as: "answer"
    patch '/questions/:id' => 'questions#validate_answer', as: "question"
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	
	def index
		@current_user = current_user
		@user = User.new
	end

	def search
		@items = Item.search(params[:search])
	end

  def report
		@item = Item.new
		@relation = @item.relations.new
  end

end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/_flash_messages.html.erb
<div class="flash-msgs-container">

  <% if flash["success_message"] %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    	<span aria-hidden="true">&times;</span>
    </button>
    <strong><%= flash["success_message"] %></strong>
  </div>
  <% end %>

  <% if flash["info_message"] %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    	<span aria-hidden="true">&times;</span>
    </button>
    <strong><%= flash["info_message"] %></strong>
  </div>
  <% end %>

  <% if flash["warning_message"] %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    	<span aria-hidden="true">&times;</span>
    </button>
    <strong><%= flash["warning_message"] %></strong>
  </div>
  <% end %>

  <% if flash["danger_message"] %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    	<span aria-hidden="true">&times;</span>
    </button>
    <strong><%= flash["danger_message"] %></strong>
  </div>
  <% end %>

</div>

app/views/site/_logged_index.html.erb
<h2 class="registration-main-title">Welcome <%= current_user.name %>! </h2>

<div class="row">
  <div class="col-xs-12 col-md-6">
    <%= link_to image_tag("btnPerdi.png", size: "160x80", class: "index-btns"), report_path %>
    <p>Lorem impuksj kajd ks akdajsdk qiweuq iuis site amte.</p>
  </div>
  <div class="col-xs-12 col-md-6">
    <%= image_tag("btnEncontre.png", size: "160x80", class: "index-btns") %>
    <p>Lorem impuksj kajd ks akdajsdk qiweuq iuis site amte.</p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-md-6">
    <%= image_tag("btnObjetosQPerdido.png", size: "160x80", class: "index-btns") %>
    <p>Lorem impuksj kajd ks akdajsdk qiweuq iuis site amte.</p>
  </div>
  <div class="col-xs-12 col-md-6">
    <%= image_tag("btnObjetosQEncontrado.png", size: "160x80", class: "index-btns") %>
    <p>Lorem impuksj kajd ks akdajsdk qiweuq iuis site amte.</p>
  </div>
</div>

<h2 class="registration-main-title">My reports</h2>
<p>(matches nuevos puede ir aqui... info) </p>

app/views/site/_owmi_welcome.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="landing-logo">
      <img src="https://dl.dropboxusercontent.com/u/10924302/recover-me/logo.png" alt="Owmi Logo" class="img-responsive">
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <blockquote class="blockquote-reverse quote-product-desc">
      <p>
        Register now to search for your lost things or report an object you've found.  Owmi is here to help people help each other, that is why we believe in your good will.
      </p>
    </blockquote>
  </div>
</div>

app/views/site/index.html.erb
<div class="col-md-12">
	<div class="col-md-6">
		<div class="">
		
			<%=
				render partial: ( logged_in? ?
													'/items/search_form' :
													'/site/owmi_welcome' ) #, for sending local vars
													#locals: { relation: relation }
			%>

		</div>



	</div>
	<div class="col-md-6">
		<div class="landing-resgistration-container">

			<%=
				render partial: ( logged_in? ?
													'/site/logged_index' :
													'/registration/registration' ) #, for sending local vars
													#locals: { relation: relation }
			%>

		</div>
	</div>
</div>

app/views/site/index_geo_list.html.erb
<div class="col-md-12">
	<div class="col-md-8 col-md-offset-2">
		<div>
			<h2>My Location Map</h2>
			<img id="location-map" class="img-responsive" src="#" alt="">
		</div>
		<div class="page-header">
		  <h2>List of Objects</h2>
		</div>
		<div class="list-group">
			<% @items.each do |item| %>
			  <a href="#" class="list-group-item">
			    <h4 class="list-group-item-heading">Item: <b><%= item.name %></b></h4>
			    <p class="list-group-item">Date: <b><%= item.datetime %></b></p>
			    <p class="list-group-item">Category: <b><%= item.category %></b></p>
			    <p class="list-group-item">Reward: <b><%= item.reward %></b></p>
			    <p class="list-group-item">Contact Email: <b><%= item.contact_email %></b></p>
			    <p class="list-group-item">Latitude: <b><%= item.latitude %></b></p>
			    <p class="list-group-item">Longitude: <b><%= item.longitude %></b></p>
			    <p class="list-group-item">State: <b><%= item.state %></b></p>
			  </a>
			<% end %>
		</div>
	</div>
</div>

app/views/site/index_ironhack_design.html.erb
<div class="col-md-12">
	<div class="col-md-6">

		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="landing-logo">
					<img src="https://dl.dropboxusercontent.com/u/10924302/recover-me/logo.png" alt="Owmi Logo" class="img-responsive">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<blockquote class="blockquote-reverse quote-product-desc">

				</blockquote>
			</div>
		</div>

	</div>
	<div class="col-md-6">
		<div class="landing-resgistration-container">
			<%= render :partial => '/registration/registration' %>
		</div>
	</div>
</div>

app/views/site/index_only_login.html.erb
<div class="col-md-12">
	<div class="col-md-8 col-md-offset-2">
		<% if @current_user %>
		<p>Signed in as <%= @current_user.name %></p>
		<%= link_to "Log out", logout_path, method: :delete %>
		<% else %>
		<%= render :partial => '/login/login' %>
		<% end %>
	</div>
</div>

app/views/site/index_simple_layout_page_ironhack.html.erb
<div class="col-md-12">
	<div class="col-md-6">

		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="landing-logo">
					<img src="https://dl.dropboxusercontent.com/u/10924302/recover-me/logo.png" alt="Owmi Logo" class="img-responsive">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<blockquote class="blockquote-reverse quote-product-desc">
					<p>
						Register now to search for your lost things or report an object you've found.  Owmi is here to help people help each other, that is why we believe in your good will.
					</p>
				</blockquote>
			</div>
		</div>

	</div>
	<div class="col-md-6">
		<div class="landing-resgistration-container">
			<%= render :partial => '/registration/registration' %>
		</div>
	</div>
</div>

app/views/site/report.html.erb
  <div class="col-xs-10 col-xs-offset-1 ">
  <h2>Report Lost Object</h2>
  <div class="panel-group main-panel" id="accordion" role="tablist" aria-multiselectable="true">

    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <span class="glyphicon glyphicon-list-alt pull-right" aria-hidden="true"></span>
            Step 1) Basic Information (Mandatory)
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
          <%= render :partial => '/items/report_lost_basic' %>
        </div>
      </div>
    </div>


    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingTwo">
        <h4 class="panel-title">
          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            <span class="glyphicon glyphicon-lock pull-right" aria-hidden="true"></span>
            Step 2) Additional Information (Optional)
          </a>
        </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
        <div class="panel-body">
          - Additional information as images, desc, etc...
        </div>
      </div>
    </div>


    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingThree">
        <h4 class="panel-title">
          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            <span class="glyphicon glyphicon-comment pull-right" aria-hidden="true"></span>
            Step 3) Questions if item is found (Optional)
          </a>
        </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
        <div class="panel-body">
          - Questions when reporting lost objects not neccesary... 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/site/search.html.erb
<div class="col-md-12">
  <div class="col-md-8 col-md-offset-2">
    <h4>Search results...</h4>
     <div class="list-group">
      <div class="list-group">


        <% @items.each do |item| %>
          <a href=<%= item_path(item) %> class="list-group-item">
          <h4 class="list-group-item-heading">
            <b><span class="item-name"><%= item.name %></span></b>
          </h4>
            <div class="media">
              <div class="media-left">
                <img class="media-object" src=<%=item.avatar.url(:thumb)%> alt="...">
              </div>
              <div class="media-body">
                <h4 class="media-heading">Media heading</h4>
                <%= item.name %>
                <%= item.contact_email %>
                <%= item.state %>
                <%= item.reward %>
                <%= item.latitude %>
                <%= item.longitude %>
              </div>
            </div>
          </a>
        <% end %>


      </div>
    </div>
  </div>
</div>